// Sol system static data — ported from src/data/sol-data.ts

use crate::system_generator::{
    AsteroidBeltData, BodyData, CometData, MoonData, RingData, SystemData,
};

pub fn get_sol_system() -> SystemData {
    SystemData {
        name: "Sol System".to_string(),
        bodies: vec![
            BodyData {
                name: "Sol".to_string(),
                body_type: "Star".to_string(),
                distance: 0.0,
                e: 0.0,
                period: 0.0,
                radius: 695700.0,
                mass: 1.989e30,
                color: "#ffdd44".to_string(),
                emissive: Some(true),
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Mercury".to_string(),
                body_type: "Planet".to_string(),
                distance: 0.387,
                e: 0.206,
                period: 0.241,
                radius: 2440.0,
                mass: 3.301e23,
                color: "#aaaaaa".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Venus".to_string(),
                body_type: "Planet".to_string(),
                distance: 0.723,
                e: 0.007,
                period: 0.615,
                radius: 6052.0,
                mass: 4.867e24,
                color: "#ddaa66".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Earth".to_string(),
                body_type: "Planet".to_string(),
                distance: 1.0,
                e: 0.017,
                period: 1.0,
                radius: 6371.0,
                mass: 5.972e24,
                color: "#4488cc".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Luna".to_string(),
                    distance: 0.04,
                    e: 0.055,
                    period: 0.0748,
                    radius: 1737.0,
                    mass: 7.342e22,
                    color: "#999999".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Mars".to_string(),
                body_type: "Planet".to_string(),
                distance: 1.524,
                e: 0.093,
                period: 1.881,
                radius: 3390.0,
                mass: 6.417e23,
                color: "#cc5533".to_string(),
                emissive: None,
                moons: vec![
                    MoonData {
                        name: "Phobos".to_string(),
                        distance: 0.02,
                        e: 0.015,
                        period: 0.0008,
                        radius: 11.0,
                        mass: 1.0659e16,
                        color: "#887766".to_string(),
                    },
                    MoonData {
                        name: "Deimos".to_string(),
                        distance: 0.03,
                        e: 0.0002,
                        period: 0.003,
                        radius: 6.0,
                        mass: 1.4762e15,
                        color: "#887766".to_string(),
                    },
                ],
                rings: None,
            },
            BodyData {
                name: "Jupiter".to_string(),
                body_type: "Planet".to_string(),
                distance: 5.203,
                e: 0.049,
                period: 11.86,
                radius: 69911.0,
                mass: 1.898e27,
                color: "#ddaa77".to_string(),
                emissive: None,
                moons: vec![
                    MoonData {
                        name: "Io".to_string(),
                        distance: 0.06,
                        e: 0.004,
                        period: 0.00484,
                        radius: 1822.0,
                        mass: 8.932e22,
                        color: "#ddcc44".to_string(),
                    },
                    MoonData {
                        name: "Europa".to_string(),
                        distance: 0.08,
                        e: 0.009,
                        period: 0.00972,
                        radius: 1561.0,
                        mass: 4.8e22,
                        color: "#ccccdd".to_string(),
                    },
                    MoonData {
                        name: "Ganymede".to_string(),
                        distance: 0.1,
                        e: 0.001,
                        period: 0.01959,
                        radius: 2634.0,
                        mass: 1.482e23,
                        color: "#aaaaaa".to_string(),
                    },
                    MoonData {
                        name: "Callisto".to_string(),
                        distance: 0.13,
                        e: 0.007,
                        period: 0.0457,
                        radius: 2410.0,
                        mass: 1.076e23,
                        color: "#777788".to_string(),
                    },
                ],
                rings: Some(RingData {
                    inner: 1.3,
                    outer: 1.8,
                    color: None,
                    opacity: Some(0.15),
                    tilt: Some(3.1),
                }),
            },
            BodyData {
                name: "Saturn".to_string(),
                body_type: "Planet".to_string(),
                distance: 9.537,
                e: 0.054,
                period: 29.46,
                radius: 58232.0,
                mass: 5.683e26,
                color: "#ccbb77".to_string(),
                emissive: None,
                moons: vec![
                    MoonData {
                        name: "Titan".to_string(),
                        distance: 0.1,
                        e: 0.029,
                        period: 0.0437,
                        radius: 2575.0,
                        mass: 1.3452e23,
                        color: "#cc9944".to_string(),
                    },
                    MoonData {
                        name: "Enceladus".to_string(),
                        distance: 0.04,
                        e: 0.005,
                        period: 0.00375,
                        radius: 252.0,
                        mass: 1.08e20,
                        color: "#ddddee".to_string(),
                    },
                ],
                rings: Some(RingData {
                    inner: 1.2,
                    outer: 2.3,
                    color: Some("#ccbb88".to_string()),
                    opacity: None,
                    tilt: Some(26.7),
                }),
            },
            BodyData {
                name: "Uranus".to_string(),
                body_type: "Planet".to_string(),
                distance: 19.19,
                e: 0.047,
                period: 84.01,
                radius: 25362.0,
                mass: 8.681e25,
                color: "#88bbcc".to_string(),
                emissive: None,
                moons: vec![
                    MoonData {
                        name: "Miranda".to_string(),
                        distance: 0.04,
                        e: 0.001,
                        period: 0.00387,
                        radius: 236.0,
                        mass: 6.59e19,
                        color: "#aabbbb".to_string(),
                    },
                    MoonData {
                        name: "Titania".to_string(),
                        distance: 0.08,
                        e: 0.001,
                        period: 0.02387,
                        radius: 789.0,
                        mass: 3.527e21,
                        color: "#aaaaaa".to_string(),
                    },
                ],
                rings: Some(RingData {
                    inner: 1.6,
                    outer: 2.0,
                    color: None,
                    opacity: Some(0.12),
                    tilt: Some(97.8),
                }),
            },
            BodyData {
                name: "Neptune".to_string(),
                body_type: "Planet".to_string(),
                distance: 30.07,
                e: 0.009,
                period: 164.8,
                radius: 24622.0,
                mass: 1.024e26,
                color: "#4466cc".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Triton".to_string(),
                    distance: 0.06,
                    e: 0.0,
                    period: 0.0161,
                    radius: 1353.0,
                    mass: 2.14e22,
                    color: "#99aaaa".to_string(),
                }],
                rings: Some(RingData {
                    inner: 1.7,
                    outer: 2.5,
                    color: None,
                    opacity: Some(0.1),
                    tilt: Some(28.3),
                }),
            },
            BodyData {
                name: "Ceres".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 2.77,
                e: 0.076,
                period: 4.6,
                radius: 473.0,
                mass: 9.393e20,
                color: "#888877".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Pluto".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 39.48,
                e: 0.25,
                period: 248.0,
                radius: 1188.0,
                mass: 1.303e22,
                color: "#ccaa88".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Charon".to_string(),
                    distance: 0.05,
                    e: 0.0,
                    period: 0.01745,
                    radius: 606.0,
                    mass: 1.586e21,
                    color: "#999988".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Haumea".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 43.22,
                e: 0.189,
                period: 284.1,
                radius: 816.0,
                mass: 4.006e21,
                color: "#aaaaaa".to_string(),
                emissive: None,
                moons: vec![
                    MoonData {
                        name: "Hi'iaka".to_string(),
                        distance: 0.06,
                        e: 0.05,
                        period: 0.1345,
                        radius: 160.0,
                        mass: 1.79e19,
                        color: "#888888".to_string(),
                    },
                    MoonData {
                        name: "Namaka".to_string(),
                        distance: 0.03,
                        e: 0.25,
                        period: 0.05,
                        radius: 75.0,
                        mass: 1.79e18,
                        color: "#888888".to_string(),
                    },
                ],
                rings: None,
            },
            BodyData {
                name: "Makemake".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 45.79,
                e: 0.161,
                period: 309.9,
                radius: 715.0,
                mass: 3.1e21,
                color: "#bb9977".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "MK 2".to_string(),
                    distance: 0.03,
                    e: 0.0,
                    period: 0.049,
                    radius: 87.0,
                    mass: 4.0e18,
                    color: "#666666".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Eris".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 67.78,
                e: 0.436,
                period: 559.0,
                radius: 1163.0,
                mass: 1.66e22,
                color: "#bbbbbb".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Dysnomia".to_string(),
                    distance: 0.05,
                    e: 0.01,
                    period: 0.04384,
                    radius: 350.0,
                    mass: 8.2e19,
                    color: "#777777".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Sedna".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 506.0,
                e: 0.843,
                period: 11400.0,
                radius: 498.0,
                mass: 8.3e20,
                color: "#cc6644".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Orcus".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 39.2,
                e: 0.227,
                period: 245.0,
                radius: 479.0,
                mass: 6.32e20,
                color: "#999999".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Vanth".to_string(),
                    distance: 0.03,
                    e: 0.0,
                    period: 0.043,
                    radius: 222.0,
                    mass: 9.0e19,
                    color: "#777777".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Ixion".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 39.35,
                e: 0.244,
                period: 251.0,
                radius: 349.0,
                mass: 2.0e20,
                color: "#887766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Achlys".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 39.4,
                e: 0.183,
                period: 247.0,
                radius: 350.0,
                mass: 3.0e20,
                color: "#888888".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Huya".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 39.4,
                e: 0.28,
                period: 247.0,
                radius: 207.0,
                mass: 1.5e20,
                color: "#776655".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Mani".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 41.7,
                e: 0.15,
                period: 269.0,
                radius: 400.0,
                mass: 3.0e20,
                color: "#998877".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Salacia".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 42.2,
                e: 0.11,
                period: 274.0,
                radius: 423.0,
                mass: 4.86e20,
                color: "#888899".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Actaea".to_string(),
                    distance: 0.03,
                    e: 0.0,
                    period: 0.042,
                    radius: 197.0,
                    mass: 7.0e19,
                    color: "#777788".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Goibniu".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 43.0,
                e: 0.07,
                period: 282.0,
                radius: 340.0,
                mass: 2.0e20,
                color: "#666666".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Varuna".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 43.1,
                e: 0.051,
                period: 283.0,
                radius: 340.0,
                mass: 5.9e20,
                color: "#aa8877".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Quaoar".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 43.7,
                e: 0.04,
                period: 289.0,
                radius: 555.0,
                mass: 1.21e21,
                color: "#bb9977".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Weywot".to_string(),
                    distance: 0.04,
                    e: 0.0,
                    period: 0.056,
                    radius: 83.0,
                    mass: 1.0e19,
                    color: "#888877".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Chaos".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 45.9,
                e: 0.107,
                period: 309.0,
                radius: 225.0,
                mass: 1.0e20,
                color: "#777777".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Varda".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 46.1,
                e: 0.14,
                period: 313.0,
                radius: 370.0,
                mass: 2.66e20,
                color: "#998877".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Ilmare".to_string(),
                    distance: 0.03,
                    e: 0.0,
                    period: 0.041,
                    radius: 202.0,
                    mass: 6.0e19,
                    color: "#887766".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Aya".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 47.2,
                e: 0.13,
                period: 324.0,
                radius: 384.0,
                mass: 2.0e20,
                color: "#aa6655".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Chiminigagua".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 58.9,
                e: 0.39,
                period: 449.0,
                radius: 371.0,
                mass: 2.5e20,
                color: "#777766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Gonggong".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 67.5,
                e: 0.5,
                period: 553.0,
                radius: 615.0,
                mass: 1.75e21,
                color: "#aa7755".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Xiangliu".to_string(),
                    distance: 0.03,
                    e: 0.29,
                    period: 0.039,
                    radius: 50.0,
                    mass: 5.0e18,
                    color: "#777766".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Dziewanna".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 69.3,
                e: 0.54,
                period: 591.0,
                radius: 252.0,
                mass: 1.0e20,
                color: "#887766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Gkunllhomdima".to_string(),
                body_type: "Dwarf Planet".to_string(),
                distance: 72.7,
                e: 0.48,
                period: 620.0,
                radius: 316.0,
                mass: 1.36e20,
                color: "#666677".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Goehu".to_string(),
                    distance: 0.03,
                    e: 0.0,
                    period: 0.04,
                    radius: 50.0,
                    mass: 5.0e18,
                    color: "#555566".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Okyrhoe".to_string(),
                body_type: "Centaur".to_string(),
                distance: 8.4,
                e: 0.307,
                period: 24.2,
                radius: 25.0,
                mass: 6.0e16,
                color: "#666655".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Thereus".to_string(),
                body_type: "Centaur".to_string(),
                distance: 10.6,
                e: 0.2,
                period: 34.5,
                radius: 38.0,
                mass: 2.5e17,
                color: "#888877".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Echeclus".to_string(),
                body_type: "Centaur".to_string(),
                distance: 10.7,
                e: 0.457,
                period: 35.0,
                radius: 32.0,
                mass: 1.5e17,
                color: "#777766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Elatus".to_string(),
                body_type: "Centaur".to_string(),
                distance: 11.8,
                e: 0.385,
                period: 40.6,
                radius: 25.0,
                mass: 6.0e16,
                color: "#aa6644".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Chiron".to_string(),
                body_type: "Centaur".to_string(),
                distance: 13.7,
                e: 0.383,
                period: 50.4,
                radius: 109.0,
                mass: 4.8e18,
                color: "#889999".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Chariklo".to_string(),
                body_type: "Centaur".to_string(),
                distance: 15.8,
                e: 0.167,
                period: 62.9,
                radius: 124.0,
                mass: 7.0e18,
                color: "#887766".to_string(),
                emissive: None,
                moons: vec![],
                rings: Some(RingData {
                    inner: 1.5,
                    outer: 1.7,
                    color: None,
                    opacity: Some(0.3),
                    tilt: Some(45.0),
                }),
            },
            BodyData {
                name: "Bienor".to_string(),
                body_type: "Centaur".to_string(),
                distance: 16.5,
                e: 0.201,
                period: 67.3,
                radius: 79.0,
                mass: 2.0e18,
                color: "#777777".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Asbolus".to_string(),
                body_type: "Centaur".to_string(),
                distance: 18.1,
                e: 0.62,
                period: 76.9,
                radius: 40.0,
                mass: 3.0e17,
                color: "#666666".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Crantor".to_string(),
                body_type: "Centaur".to_string(),
                distance: 19.5,
                e: 0.281,
                period: 85.8,
                radius: 30.0,
                mass: 1.0e17,
                color: "#888888".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Pelion".to_string(),
                body_type: "Centaur".to_string(),
                distance: 20.0,
                e: 0.135,
                period: 89.8,
                radius: 18.0,
                mass: 2.0e16,
                color: "#777766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Pholus".to_string(),
                body_type: "Centaur".to_string(),
                distance: 20.3,
                e: 0.571,
                period: 91.8,
                radius: 95.0,
                mass: 5.0e17,
                color: "#aa5533".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Nessus".to_string(),
                body_type: "Centaur".to_string(),
                distance: 24.7,
                e: 0.52,
                period: 122.4,
                radius: 30.0,
                mass: 1.0e17,
                color: "#885544".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Hylonome".to_string(),
                body_type: "Centaur".to_string(),
                distance: 25.1,
                e: 0.244,
                period: 126.2,
                radius: 37.0,
                mass: 2.0e17,
                color: "#777788".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Amycus".to_string(),
                body_type: "Centaur".to_string(),
                distance: 25.1,
                e: 0.391,
                period: 125.1,
                radius: 48.0,
                mass: 4.0e17,
                color: "#888877".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Cyllarus".to_string(),
                body_type: "Centaur".to_string(),
                distance: 26.1,
                e: 0.381,
                period: 133.4,
                radius: 31.0,
                mass: 1.0e17,
                color: "#996655".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Eros".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 1.458,
                e: 0.223,
                period: 1.76,
                radius: 8.0,
                mass: 6.69e15,
                color: "#bbaa88".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Gaspra".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.209,
                e: 0.173,
                period: 3.29,
                radius: 6.0,
                mass: 2.5e15,
                color: "#aaaaaa".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Vesta".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.362,
                e: 0.088,
                period: 3.63,
                radius: 263.0,
                mass: 2.59e20,
                color: "#aaaaaa".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Fortuna".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.442,
                e: 0.158,
                period: 3.82,
                radius: 106.0,
                mass: 1.27e19,
                color: "#666655".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Amphitrite".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.554,
                e: 0.074,
                period: 4.08,
                radius: 104.0,
                mass: 1.18e19,
                color: "#999988".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Eunomia".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.644,
                e: 0.187,
                period: 4.3,
                radius: 116.0,
                mass: 3.25e19,
                color: "#bbaa99".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Juno".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.669,
                e: 0.256,
                period: 4.35,
                radius: 124.0,
                mass: 2.7e19,
                color: "#aaaaaa".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Bamberga".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.685,
                e: 0.341,
                period: 4.38,
                radius: 111.0,
                mass: 1.0e19,
                color: "#777766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Pallas".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.769,
                e: 0.23,
                period: 4.61,
                radius: 256.0,
                mass: 2.05e20,
                color: "#888888".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Thisbe".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.769,
                e: 0.165,
                period: 4.6,
                radius: 116.0,
                mass: 1.83e19,
                color: "#777766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Herculina".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.77,
                e: 0.179,
                period: 4.6,
                radius: 84.0,
                mass: 2.29e19,
                color: "#999988".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Ida".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.864,
                e: 0.043,
                period: 4.84,
                radius: 16.0,
                mass: 4.2e16,
                color: "#aaaaaa".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Dactyl".to_string(),
                    distance: 0.03,
                    e: 0.0,
                    period: 0.04,
                    radius: 1.0,
                    mass: 4.0e13,
                    color: "#999999".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Psyche".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 2.924,
                e: 0.134,
                period: 5.0,
                radius: 111.0,
                mass: 2.29e19,
                color: "#ccbbaa".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Interamnia".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 3.058,
                e: 0.156,
                period: 5.34,
                radius: 166.0,
                mass: 3.8e19,
                color: "#888877".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "52 Europa".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 3.093,
                e: 0.111,
                period: 5.45,
                radius: 158.0,
                mass: 3.27e19,
                color: "#777766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Hygiea".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 3.15,
                e: 0.111,
                period: 5.56,
                radius: 217.0,
                mass: 8.67e19,
                color: "#777777".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Euphrosyne".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 3.159,
                e: 0.216,
                period: 5.61,
                radius: 134.0,
                mass: 1.7e19,
                color: "#888888".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Davida".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 3.161,
                e: 0.189,
                period: 5.61,
                radius: 145.0,
                mass: 3.84e19,
                color: "#777766".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
            BodyData {
                name: "Sylvia".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 3.477,
                e: 0.094,
                period: 6.48,
                radius: 137.0,
                mass: 1.48e19,
                color: "#666655".to_string(),
                emissive: None,
                moons: vec![
                    MoonData {
                        name: "Romulus".to_string(),
                        distance: 0.04,
                        e: 0.0,
                        period: 0.058,
                        radius: 12.0,
                        mass: 1.0e16,
                        color: "#777766".to_string(),
                    },
                    MoonData {
                        name: "Remus".to_string(),
                        distance: 0.03,
                        e: 0.0,
                        period: 0.033,
                        radius: 4.0,
                        mass: 1.0e15,
                        color: "#777766".to_string(),
                    },
                ],
                rings: None,
            },
            BodyData {
                name: "Patroclus".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 5.21,
                e: 0.14,
                period: 11.92,
                radius: 57.0,
                mass: 1.36e18,
                color: "#777766".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Menoetius".to_string(),
                    distance: 0.03,
                    e: 0.0,
                    period: 0.041,
                    radius: 52.0,
                    mass: 1.2e18,
                    color: "#777766".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Hektor".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 5.272,
                e: 0.023,
                period: 12.1,
                radius: 125.0,
                mass: 7.9e18,
                color: "#776655".to_string(),
                emissive: None,
                moons: vec![MoonData {
                    name: "Skamandrios".to_string(),
                    distance: 0.03,
                    e: 0.0,
                    period: 0.038,
                    radius: 6.0,
                    mass: 5.0e15,
                    color: "#887766".to_string(),
                }],
                rings: None,
            },
            BodyData {
                name: "Agamemnon".to_string(),
                body_type: "Asteroid".to_string(),
                distance: 5.28,
                e: 0.07,
                period: 12.1,
                radius: 84.0,
                mass: 3.0e18,
                color: "#888877".to_string(),
                emissive: None,
                moons: vec![],
                rings: None,
            },
        ],
        comets: vec![
            CometData {
                name: "Halley".to_string(),
                a: 17.83,
                e: 0.967,
                period: 75.3,
                inc: 4.0,
                node: 58.42,
                peri: 111.33,
                color: "#99ccff".to_string(),
                mass: 2.2e14,
            },
            CometData {
                name: "Hale-Bopp".to_string(),
                a: 186.0,
                e: 0.995,
                period: 2533.0,
                inc: 3.0,
                node: 282.47,
                peri: 130.59,
                color: "#aaddff".to_string(),
                mass: 1.3e16,
            },
            CometData {
                name: "Encke".to_string(),
                a: 2.22,
                e: 0.848,
                period: 3.3,
                inc: 2.0,
                node: 334.57,
                peri: 186.55,
                color: "#88bbaa".to_string(),
                mass: 2.0e13,
            },
            CometData {
                name: "Swift-Tuttle".to_string(),
                a: 26.09,
                e: 0.963,
                period: 133.3,
                inc: 5.0,
                node: 139.38,
                peri: 152.98,
                color: "#bbaaff".to_string(),
                mass: 5.0e15,
            },
            CometData {
                name: "Tempel 1".to_string(),
                a: 3.12,
                e: 0.51,
                period: 5.5,
                inc: 2.0,
                node: 68.76,
                peri: 179.19,
                color: "#aa9988".to_string(),
                mass: 7.9e13,
            },
            CometData {
                name: "Churyumov-Ger.".to_string(),
                a: 3.46,
                e: 0.678,
                period: 6.4,
                inc: 1.0,
                node: 45.93,
                peri: 14.52,
                color: "#998877".to_string(),
                mass: 1.0e13,
            },
            CometData {
                name: "Hyakutake".to_string(),
                a: 1700.0,
                e: 0.9998,
                period: 70000.0,
                inc: 3.0,
                node: 188.05,
                peri: 130.17,
                color: "#ccddff".to_string(),
                mass: 3.0e13,
            },
            CometData {
                name: "Neowise".to_string(),
                a: 358.5,
                e: 0.999,
                period: 6800.0,
                inc: 4.0,
                node: 61.01,
                peri: 37.28,
                color: "#ddeeff".to_string(),
                mass: 1.0e14,
            },
        ],
        asteroid_belts: vec![
            AsteroidBeltData {
                name: "Main Belt".to_string(),
                min_au: 2.1,
                max_au: 3.3,
                count: 1387,
                color: "#555544".to_string(),
                size: 0.25,
                max_inc: 3,
            },
            AsteroidBeltData {
                name: "Kuiper Belt - Cold Classical".to_string(),
                min_au: 42.0,
                max_au: 48.0,
                count: 1523,
                color: "#333344".to_string(),
                size: 0.3,
                max_inc: 1,
            },
            AsteroidBeltData {
                name: "Kuiper Belt - Hot Classical".to_string(),
                min_au: 30.0,
                max_au: 50.0,
                count: 1261,
                color: "#334455".to_string(),
                size: 0.3,
                max_inc: 5,
            },
            AsteroidBeltData {
                name: "Kuiper Belt - Resonant".to_string(),
                min_au: 39.0,
                max_au: 48.0,
                count: 842,
                color: "#443355".to_string(),
                size: 0.3,
                max_inc: 3,
            },
        ],
    }
}
